# config.yaml - 混合频率量价因子模型配置文件

# 模型配置
model:
  name: "mixed_frequency_factor_model"
  type: "classification"
  num_classes: 2
  
  # 多频率编码器配置
  multi_frequency_encoder:
    # 周频数据配置
    weekly:
      input_dim: 17
      hidden_dim: 128
      num_layers: 2
      dropout: 0.2
      bidirectional: true
    
    # 日频数据配置
    daily:
      input_dim: 17
      hidden_dim: 256
      num_layers: 2
      dropout: 0.2
      bidirectional: true
    
    # 日内数据配置
    intraday:
      input_dim: 17
      hidden_dim: 512
      num_layers: 2
      dropout: 0.2
      bidirectional: true
  
  # 注意力机制配置
  attention:
    num_heads: 8
    hidden_dim: 512
    dropout: 0.1
    use_residual: true
  
  # 因子提取器配置
  factor_extractor:
    num_factors: 64
    factor_dim: 128
    num_layers: 3
    activation: "relu"
    dropout: 0.3
    use_batch_norm: true
  
  # 分类器配置
  classifier:
    hidden_dims: [512, 256, 128]
    dropout: 0.4
    activation: "relu"
    use_batch_norm: true
    output_activation: "softmax"

# 数据配置
data:
  # 数据源
  source:
    train_path: "../../data/feature_set/mrmr_data_task_06_2016-01-01_2021-07-01.pq"
    alternative_paths:
      - "/data/feature_set/mrmr_data_task_06_2016-01-01_2021-07-01.pq"
      - "./data/processed/mrmr_data_task_06_2016-01-01_2021-07-01.pq"
      - "./data/raw/stock_data.csv"
    format: "parquet"
    encoding: "utf-8"
  
  # 时间范围
  time_range:
    start_date: "2016-01-01"
    end_date: "2021-07-01"
    task_id: "06"
    data_version: "mrmr"
  
  # 数据schema
  schema:
    required_columns:
      - "date"
      - "instrument"
      - "label"
    target_column: "label"
    exclude_columns:
      - "date"
      - "instrument"
      - "label"
      - "weight"
      - "market_cap"
  
  # 数据预处理
  preprocessing:
    normalize: true
    standardize: true
    fill_na_method: "forward"
    outlier_threshold: 3.0
    min_samples_per_class: 100
  
  # 数据分割
  split:
    train_ratio: 0.7
    val_ratio: 0.15
    test_ratio: 0.15
    stratify: true
    random_state: 42
  
  # 序列配置
  sequence:
    seq_len: 60
    stride: 1
    overlap: true

# 训练配置
training:
  # 基础参数
  batch_size: 64
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.00001
  
  # 优化器配置
  optimizer:
    type: "adam"
    learning_rate: 0.001
    weight_decay: 0.00001
    betas: [0.9, 0.999]
    eps: 1e-8
    amsgrad: false
  
  # 学习率调度
  scheduler:
    type: "cosine"
    T_max: 100
    eta_min: 1e-6
    warmup_epochs: 10
  
  # 损失函数
  loss:
    type: "cross_entropy"
    class_weights: null
    label_smoothing: 0.1
  
  # 训练参数
  epochs: 100
  batch_size: 64
  validation_split: 0.2
  
  # 早停配置
  early_stopping:
    patience: 15
    min_delta: 0.001
    monitor: "val_loss"
    mode: "min"
  
  # 梯度配置
  gradient:
    clip_norm: 1.0
    accumulation_steps: 1

# 验证配置
validation:
  # 验证频率
  eval_frequency: 1
  save_best_model: true
  
  # 评估指标
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "auc"
    - "confusion_matrix"
  
  # 验证数据配置
  val_batch_size: 128
  num_workers: 4

# 推理配置
inference:
  batch_size: 256
  num_workers: 4
  device: "auto"
  
  # 输出配置
  output:
    save_predictions: true
    save_probabilities: true
    save_features: false
  
  # 后处理
  postprocessing:
    threshold: 0.5
    apply_tta: false

# 模型保存和加载
model_management:
  # 保存配置
  save:
    checkpoint_dir: "./checkpoints"
    save_frequency: 5
    keep_best_only: false
    max_checkpoints: 10
  
  # 模型导出
  export:
    format: ["pytorch", "onnx"]
    export_dir: "./exports"
    optimize_for_inference: true

# 日志和监控
logging:
  # 日志级别
  level: "INFO"
  
  # 日志文件
  log_dir: "./logs"
  log_file: "training.log"
  
  # TensorBoard
  tensorboard:
    enabled: true
    log_dir: "./runs"
    log_frequency: 10
  
  # 监控指标
  monitor:
    - "train_loss"
    - "val_loss"
    - "train_accuracy"
    - "val_accuracy"
    - "learning_rate"

# 硬件配置
hardware:
  # 设备配置
  device: "auto"  # auto/cpu/cuda/mps
  gpu_ids: [0]
  
  # 并行配置
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  
  # 内存配置
  max_memory_usage: 0.8
  cache_dataset: true

# 实验配置
experiment:
  # 实验标识
  name: "mixed_frequency_factor_model"
  version: "v1.0"
  description: "混合频率量价因子模型实验"
  
  # 随机种子
  seed: 42
  deterministic: true
  
  # 标签
  tags:
    - "finance"
    - "time_series"
    - "multi_frequency"
    - "factor_model"

# 环境配置
environment:
  # Python环境
  python_version: "3.8+"
  
  # 依赖包
  required_packages:
    - "torch>=1.12.0"
    - "numpy>=1.21.0"
    - "pandas>=1.3.0"
    - "scikit-learn>=1.0.0"
    - "tensorboard>=2.8.0"
  
  # 环境变量
  env_vars:
    CUDA_VISIBLE_DEVICES: "0"
    OMP_NUM_THREADS: "8"